# Generated by Django 3.2.9 on 2021-11-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persone',
            name='name',
        ),
        migrations.AddField(
            model_name='persone',
            name='first_name',
            field=models.CharField(default=0, max_length=50, verbose_name='Contact name'),
            preserve_default=False,
        ),
    ]
