# Generated by Django 3.2.9 on 2021-11-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_auto_20211119_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='persone',
            name='last_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persone',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
    ]
