# Generated by Django 3.2.9 on 2021-11-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0004_auto_20211119_0943'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='persone',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='Full name'),
        ),
    ]
