# Generated by Django 3.2.9 on 2021-11-19 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0005_persone_full name'),
    ]

    operations = [
        migrations.AddField(
            model_name='persone',
            name='adress',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
