# Generated by Django 3.2.9 on 2021-11-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0006_persone_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persone',
            old_name='adress',
            new_name='address',
        ),
    ]
