# Generated by Django 3.2.9 on 2021-11-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0007_rename_adress_persone_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='persone',
            name='phone',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
