# Generated by Django 3.2.9 on 2021-11-19 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0008_auto_20211119_2212'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persone',
            new_name='Person',
        ),
    ]
