# Generated by Django 3.2.9 on 2021-11-20 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0010_person_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='url',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator]),
        ),
    ]
