# Generated by Django 3.2.9 on 2021-11-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0011_alter_person_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='url',
            field=models.CharField(max_length=50),
        ),
    ]
