# Generated by Django 3.2.9 on 2021-11-21 12:32

from django.db import migrations
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0012_alter_person_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=900000, null=True),
        ),
    ]
